/* export type data: {
  request: {
    "pageUrl": "https://www.bbc.com/news/articles/cj02rvvd8g2o",
    "api": "article",
    "fields": "publisher,title,text,author,keywords,images,links,meta,articleType,robots",
    "version": 3
  },
  "objects": [
    {
      "date": "Tue, 28 Jan 2025 00:33:29 GMT",
      "images": [
        {
          "naturalHeight": 0,
          "diffbotUri": "image|3|-1208803884",
          "title": "Getty Images A close-up of a herd of cows with cattlemen in shawls - one in red checks and another in blue checks - seen behind them - Nairobi, 2021",
          "url": "https://ichef.bbci.co.uk/news/1536/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp",
          "naturalWidth": 932,
          "primary": true
        },
        {
          "naturalHeight": 0,
          "diffbotUri": "image|3|1284380507",
          "title": "AFP A shop assistant wearing an orange headscarf and a white coat fills the shelves with dairy products at supermarket in Nairobi, Kenya ",
          "url": "https://ichef.bbci.co.uk/news/1536/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp",
          "naturalWidth": 722
        },
        {
          "naturalHeight": 0,
          "diffbotUri": "image|3|-467331273",
          "title": "Robert Ngukuu drives a herd of cows towards a water drinking point. A hazy, dusty landscape of scrub and trees can be seen behind them at the Satellite area in Mai Mahiu division, Nakuru county - January 2025",
          "url": "https://ichef.bbci.co.uk/news/1536/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp",
          "naturalWidth": 722
        },
        {
          "naturalHeight": 0,
          "diffbotUri": "image|3|-2134599618",
          "title": "Thin-looking cattle in a variety of colours walk in a grassy fenced field in Kajiado county",
          "url": "https://ichef.bbci.co.uk/news/1536/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp",
          "naturalWidth": 722
        },
        {
          "naturalHeight": 0,
          "diffbotUri": "image|3|386808126",
          "title": "Getty Images/BBC A woman looking at her mobile phone and the graphic BBC News Africa",
          "url": "https://ichef.bbci.co.uk/news/1536/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp",
          "naturalWidth": 722
        }
      ],
      "author": "Wycliffe Muia, BBC News & Peter Mwai, BBC Verify",
      "estimatedDate": "Tue, 28 Jan 2025 00:33:29 GMT",
      "publisherRegion": "Northern Europe",
      "icon": "https://www.bbc.com/bbcx/apple-touch-icon.png",
      "diffbotUri": "article|3|-710182526",
      "siteName": "BBC",
      "type": "article",
      "title": "Why Bill Gates is being dragged into a row over vaccinating cows in Kenya",
      "publisherCountry": "United Kingdom",
      "humanLanguage": "en",
      "meta": {
        "apple-itunes-app": "app-id=364147881, app-argument=https://www.bbc.com/news/articles/cj02rvvd8g2o",
        "theme-color": "#ffffff",
        "al:ios:app_name": "BBC: World News & Stories",
        "canonical-url": "https://www.bbc.com/news/articles/cj02rvvd8g2o",
        "al:android:package": "bbc.mobile.news.ww",
        "description": "Why there is growing scepticism in Kenya over a plan to vaccinate the national herd.",
        "title": "Why Bill Gates is being dragged into a row over vaccinating cows in Kenya",
        "al:ios:url": "bbcx://news/articles/cj02rvvd8g2o",
        "al:web:url": "https://bbc.com/news/articles/cj02rvvd8g2o",
        "version": "2.14.1+2",
        "al:ios:app_store_id": "364147881",
        "msapplication-TileColor": "#da532c",
        "al:android:url": "bbcx://news/articles/cj02rvvd8g2o",
        "next-head-count": "36",
        "twitter": {
          "twitter:card": "summary_large_image",
          "twitter:image:alt": "A close-up of a herd of cows with cattlemen in shawls - one in red checks and another in blue checks - seen behind them - Nairobi, 2021",
          "twitter:title": "Why Bill Gates is being dragged into a row over vaccinating cows in Kenya",
          "twitter:description": "Why there is growing scepticism in Kenya over a plan to vaccinate the national herd.",
          "twitter:image:src": "https://ichef.bbci.co.uk/news/1024/branded_news/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg"
        },
        "viewport": "width=device-width",
        "microdata": {
          "datePublished": "2025-01-28T00:33:29.416Z",
          "image": {
            "@type": "ImageObject",
            "width": 1024,
            "url": "https://ichef.bbci.co.uk/news/1024/branded_news/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg",
            "height": 576
          },
          "@type": "ReportageNewsArticle",
          "author": [
            {
              "@type": "Person",
              "name": "Wycliffe Muia, BBC News & Peter Mwai, BBC Verify"
            }
          ],
          "description": "Why there is growing scepticism in Kenya over a plan to vaccinate the national herd.",
          "publisher": {
            "@type": "NewsMediaOrganization",
            "name": "BBC News",
            "logo": {
              "@type": "ImageObject",
              "url": "https://static.files.bbci.co.uk/ws/simorgh-assets/public/news/images/metadata/poster-1024x576.png"
            },
            "publishingPrinciples": "http://www.bbc.co.uk/news/help-41670342"
          },
          "dateModified": "2025-01-28T00:33:29.416Z",
          "mainEntityOfPage": "https://www.bbc.com/news/articles/cj02rvvd8g2o",
          "@context": "http://schema.org",
          "headline": "Why Bill Gates is being dragged into a row over vaccinating cows in Kenya",
          "url": "https://www.bbc.com/news/articles/cj02rvvd8g2o",
          "thumbnailUrl": "https://ichef.bbci.co.uk/news/1024/branded_news/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg"
        },
        "og": {
          "og:image": "https://ichef.bbci.co.uk/news/1024/branded_news/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg",
          "og:image:alt": "A close-up of a herd of cows with cattlemen in shawls - one in red checks and another in blue checks - seen behind them - Nairobi, 2021",
          "og:title": "Why Bill Gates is being dragged into a row over vaccinating cows in Kenya",
          "og:description": "Why there is growing scepticism in Kenya over a plan to vaccinate the national herd."
        },
        "robots": "NOODP, NOYDIR",
        "al:android:app_name": "BBC: World News & Stories"
      },
      "pageUrl": "https://www.bbc.com/news/articles/cj02rvvd8g2o",
      "html": "<h1>Backlash in Kenya over livestock vaccines and belching cows</h1>\n<p>Nairobi</p>\n<figure><img src=\"https://www.bbc.com/bbcx/grey-placeholder.png\"></img><figcaption>Getty Images A close-up of a herd of cows with cattlemen in shawls - one in red checks and another in blue checks - seen behind them - Nairobi, 2021 </figcaption><img alt=\"Getty Images A close-up of a herd of cows with cattlemen in shawls - one in red checks and another in blue checks - seen behind them - Nairobi, 2021\" sizes=\"(min-width: 1280px) 50vw, (min-width: 1008px) 66vw, 96vw\" src=\"https://ichef.bbci.co.uk/news/1536/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp\" srcset=\"https://ichef.bbci.co.uk/news/240/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 240w,https://ichef.bbci.co.uk/news/320/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 320w,https://ichef.bbci.co.uk/news/480/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 480w,https://ichef.bbci.co.uk/news/640/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 640w,https://ichef.bbci.co.uk/news/800/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 800w,https://ichef.bbci.co.uk/news/1024/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 1024w,https://ichef.bbci.co.uk/news/1536/cpsprodpb/e0f9/live/50688d80-dc48-11ef-803a-cd9ff43466db.jpg.webp 1536w\"></img></figure>\n<p>An ambitious initiative to vaccinate all livestock in Kenya is due to kick off this week amid fierce resistance from farmers that is being driven by misleading claims about the vaccines.</p>\n<p>It will cost farmers nothing to get their animals vaccinated as the government says it is footing the bill.</p>\n<p>But Robert Nkukuu, who keeps cattle in the Mai Mahiu area of Nakuru county - some 50km (30 miles) north-west of the capital, Nairobi, explained how it had become a toxic issue since President William Ruto announced the plan last November.</p>\n<p>&quot;If the community here learns you are pro-vaccination they will slay you just now. So stop talking about it, we don't want it,&quot; he told the BBC.</p>\n<p>The government's aim is to vaccinate at least 22 million cattle and 50 million goats and sheep over three years.</p>\n<p>Currently only 10% of the national herd get the necessary vaccinations and the authorities say they want to raise that rate to 85% to make Kenya's livestock products eligible for export.</p>\n<p>The president, who is a farm owner and has several big herds himself, has said the vaccines are vital for expanding the sector by controlling foot-and-mouth disease in cattle and peste des petits ruminants (PPR) - also known as sheep and goat plague.</p>\n<p>But some of those who oppose the programme believe Microsoft co-founder Bill Gates is funding it, fuelled by <a href=\"https://x.com/jimNjue_/status/1869023751633080387\">people sharing videos of interviews</a> featuring him talking about vaccinating cows to control methane emissions.</p>\n<figure><img src=\"https://www.bbc.com/bbcx/grey-placeholder.png\"></img><figcaption>AFP A shop assistant wearing an orange headscarf and a white coat fills the shelves with dairy products at supermarket in Nairobi, Kenya </figcaption><img alt=\"AFP A shop assistant wearing an orange headscarf and a white coat fills the shelves with dairy products at supermarket in Nairobi, Kenya \" sizes=\"(min-width: 1280px) 50vw, (min-width: 1008px) 66vw, 96vw\" src=\"https://ichef.bbci.co.uk/news/1536/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp\" srcset=\"https://ichef.bbci.co.uk/news/240/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 240w,https://ichef.bbci.co.uk/news/320/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 320w,https://ichef.bbci.co.uk/news/480/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 480w,https://ichef.bbci.co.uk/news/640/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 640w,https://ichef.bbci.co.uk/news/800/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 800w,https://ichef.bbci.co.uk/news/1024/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 1024w,https://ichef.bbci.co.uk/news/1536/cpsprodpb/8070/live/c34a3b40-dc49-11ef-803a-cd9ff43466db.jpg.webp 1536w\"></img></figure>\n<p>Methane expelled by livestock belching and farting contributes about 15% of global emissions each year, UN estimates show. It is the most common greenhouse gas after carbon dioxide (CO2).</p>\n<p>Jonathan Mueke, a senior official in Kenya's agriculture ministry, has denied that Gates is involved in the livestock vaccination programme - adding that neither the US billionaire and philanthropist nor other foreign sources have provided funding.</p>\n<p>But this has not stopped the conspiracy theories being circulated on social media, often by high-profile personalities.</p>\n<p>Caleb Karuga, a former journalist and now an influential farmer, <a href=\"https://x.com/jimNjue_/status/1869023751633080387\">posted on X </a>that he would resist the jabs, saying no-one will vaccinate his livestock just &quot;because Bill Gates said so&quot;.</p>\n<p>Ledama Olekina, an opposition senator and prominent Maasai pastoralist, <a href=\"https://x.com/ledamalekina/status/1855632388648247296\">wrote on X</a>: &quot;There [are] millions of cows in Europe and America and none of them are being vaccinated for farting &hellip; mine will not be vaccinated.&quot;</p>\n<p>Gates has previously invested in projects to reduce methane emissions from cattle and <a href=\"https://www.bbc.co.uk/news/business-64382400\">is funding a US-based company looking to develop a vaccine</a>, as are other US investors.</p>\n<p>But Prof Ermias Kebreab from the University of California, Davis in the US, who has researched how to reduce methane emissions from livestock, told the BBC there was currently no livestock vaccine for reducing methane emissions in use.</p>\n<p>&quot;I wish we had one but that is still in development - and no-one has reached [the stage of] testing in animals yet,&quot; he said.</p>\n<p>However, such assurances have done little to quell misunderstanding about the motives of the vaccine campaign.</p>\n<p>The distrust is being pushed by some opposition politicians, who have said the vaccines will alter the genetic make-up of livestock, potentially resulting in defective animals.</p>\n<p>&quot;Ruto is advancing a sinister foreign agenda. This plan is reckless and must be stopped,&quot; said Kalonzo Musyoka, an opposition leader, not long after the initiative was announced.</p>\n<p>When the BBC asked Musyoka about the specific claims that the vaccines could be harmful to the cattle, his spokesperson said the vaccination campaign was a &quot;violation of the constitution&quot;.</p>\n<p>He added that it had been &quot;shrouded in secrecy&quot; and the government had not shared details about resources, implementation or technical details about the vaccines.</p>\n<p>The suggestion that livestock vaccines will genetically change animals is misleading, according to Prof Ermias.</p>\n<p>&quot;It is very similar to people getting vaccinated to fight against various diseases. There is no report that it causes deformities or alters DNA,&quot; the academic told the BBC.</p>\n<figure><img src=\"https://www.bbc.com/bbcx/grey-placeholder.png\"></img><img alt=\"Robert Ngukuu drives a herd of cows towards a water drinking point. A hazy, dusty landscape of scrub and trees can be seen behind them at the Satellite area in Mai Mahiu division, Nakuru county - January 2025\" sizes=\"(min-width: 1280px) 50vw, (min-width: 1008px) 66vw, 96vw\" src=\"https://ichef.bbci.co.uk/news/1536/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp\" srcset=\"https://ichef.bbci.co.uk/news/240/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 240w,https://ichef.bbci.co.uk/news/320/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 320w,https://ichef.bbci.co.uk/news/480/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 480w,https://ichef.bbci.co.uk/news/640/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 640w,https://ichef.bbci.co.uk/news/800/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 800w,https://ichef.bbci.co.uk/news/1024/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 1024w,https://ichef.bbci.co.uk/news/1536/cpsprodpb/2449/live/7fe290e0-dc4a-11ef-803a-cd9ff43466db.jpg.webp 1536w\"></img><figcaption>Robert Ngukuu drives a herd of cows towards a water drinking point. A hazy, dusty landscape of scrub and trees can be seen behind them at the Satellite area in Mai Mahiu division, Nakuru county - January 2025</figcaption></figure>\n<p>President Ruto has dismissed the views of those opposing the vaccinations as &quot;simply misguided, unreasonable and possibly stupid&quot;.</p>\n<p>&quot;All of us who have been vaccinated, has anyone stopped farting?&quot; Ruto said as he dismissed the methane claims as &quot;nonsense&quot;.</p>\n<p>Yet analysts say the spread of such conspiracy theories is down to poor communication by Ruto himself as well as low trust in his government following anti-tax protests last year and a series of corruption scandals.</p>\n<p>The government has faced a huge backlash over tax increases brought in since Ruto became president in 2022 - making it very unpopular. Last June it was <a href=\"https://www.bbc.co.uk/news/articles/ce77ld43lngo\">forced to withdraw a controversial finance bill</a> that would have included more tax increases.</p>\n<p>Alphonce Shiundu, Kenya editor at fact-checking organisation AfricaCheck, says the government was now facing a &quot;trust deficiency&quot; in the way it communicated the livestock campaign.</p>\n<p>When Ruto <a href=\"https://www.president.go.ke/president-ruto-announces-nationwide-livestock-vaccination/\">first announced it</a>, details were scant - and it was not clear what the animals would be vaccinated against.</p>\n<p>This is when tools that monitor social media posts on X show there was a clear spike in mentions of both Gates and cows by accounts with their location listed as Kenya.</p>\n<p>The furore grew into a matter of national debate, with cartoonists even pushing for cows' rights on social media with comical images captioned &quot;my fart, my choice&quot;.</p>\n<p>The Kenya Veterinary Association (KVA) has called on the government to halt the vaccination exercise and conduct a public awareness campaign first.</p>\n<p>&quot;The politicisation of the vaccination exercise has adversely affected the entire campaign, thus distracting the public from the goal of controlling diseases,&quot; Dr Kelvin Osore, KVA chairperson, told the BBC.</p>\n<p>But Dr Allan Azegele, the director of veterinary services at the agriculture ministry, said it could not be delayed given the recent severe outbreak of foot-and-mouth in western areas.</p>\n<p>This has forced several livestock markets to close this month - and the authorities have imposed strict quarantine measures in those places.</p>\n<p>&quot;We cannot wait&hellip; because it is more expensive to respond to outbreaks. We have to be proactive rather than reactive,&quot; Dr Azegele told the BBC.</p>\n<p>He said foot-and-mouth had no specific treatment, making prevention through vaccination crucial.</p>\n<figure><img src=\"https://www.bbc.com/bbcx/grey-placeholder.png\"></img><img alt=\"Thin-looking cattle in a variety of colours walk in a grassy fenced field in Kajiado county\" sizes=\"(min-width: 1280px) 50vw, (min-width: 1008px) 66vw, 96vw\" src=\"https://ichef.bbci.co.uk/news/1536/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp\" srcset=\"https://ichef.bbci.co.uk/news/240/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 240w,https://ichef.bbci.co.uk/news/320/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 320w,https://ichef.bbci.co.uk/news/480/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 480w,https://ichef.bbci.co.uk/news/640/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 640w,https://ichef.bbci.co.uk/news/800/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 800w,https://ichef.bbci.co.uk/news/1024/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 1024w,https://ichef.bbci.co.uk/news/1536/cpsprodpb/fb46/live/51e429a0-dc4b-11ef-803a-cd9ff43466db.jpg.webp 1536w\"></img><figcaption>Thin-looking cattle in a variety of colours walk in a grassy fenced field in Kajiado county</figcaption></figure>\n<p>Agriculture Minister Mutahi Kagwe has sought to reassure everyone that the exercise will be voluntary and has pledged to engage all stakeholders to &quot;cure misinformation&quot; surrounding the issue.</p>\n<p>The government has also been reassuring the public that the vaccines are being produced locally.</p>\n<p>But some farmers are still vowing to resist the vaccination drive, citing possible foreign influence and mistrust of the government.</p>\n<p>David Tiriki, a livestock farmer in Kajiado county, south of Nairobi, told the BBC that he would not allow his animals to be inoculated, citing safety fears.</p>\n<p>&quot;I suspect someone is trying to introduce a virus to our livestock so that the rich can start selling the cure to poor farmers who might not even afford it,&quot; he said.</p>\n<p>The BBC did speak to one small-scale farmer from Makueni county, south-east of Nairobi, who welcomed the initiative.</p>\n<p>But Ngemu Musau urged the government to make the whole process more transparent.</p>\n<p>&quot;I want assurance that my cattle will be OK after the vaccine,&quot; he told the BBC.</p>\n<p>&quot;There is a need for the government to conduct intensive public awareness campaigns.&quot;</p>\n<h2>You may also be interested in: </h2>\n<ul><li><a href=\"https://www.bbc.com/news/articles/cz4xn7yqe25o\">Vet recounts wild tales of working in Kenya</a></li><li><a href=\"https://www.bbc.com/news/articles/c999n2nyvwlo\">Kenya rolls out poison in bid to cull a million crows</a></li><li><a href=\"https://www.bbc.com/news/articles/c133r4gyx1no\">How a Kenyan farmer became a champion of climate change denial</a></li><li><a href=\"https://www.bbc.co.uk/news/world-africa-62244844\">Why farmers like William Ruto's big ambitions</a></li><li><a href=\"https://www.bbc.co.uk/news/articles/ck77g7v2dwyo\">Kenyan president's humbling shows power of African youth</a></li></ul>\n<figure><img src=\"https://www.bbc.com/bbcx/grey-placeholder.png\"></img><figcaption>Getty Images/BBC A woman looking at her mobile phone and the graphic BBC News Africa </figcaption><img alt=\"Getty Images/BBC A woman looking at her mobile phone and the graphic BBC News Africa\" sizes=\"(min-width: 1280px) 50vw, (min-width: 1008px) 66vw, 96vw\" src=\"https://ichef.bbci.co.uk/news/1536/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp\" srcset=\"https://ichef.bbci.co.uk/news/240/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 240w,https://ichef.bbci.co.uk/news/320/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 320w,https://ichef.bbci.co.uk/news/480/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 480w,https://ichef.bbci.co.uk/news/640/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 640w,https://ichef.bbci.co.uk/news/800/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 800w,https://ichef.bbci.co.uk/news/1024/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 1024w,https://ichef.bbci.co.uk/news/1536/cpsprodpb/0a19/live/7c722dc0-089d-11ef-b9d8-4f52aebe147d.jpg.webp 1536w\"></img></figure>\n<p><i>Go to </i><a href=\"http://bbcafrica.com/\"><i>BBCAfrica.com</i></a><i> for more news from the African continent.</i></p>\n<p><i>Follow us on Twitter </i><a href=\"https://twitter.com/BBCAfrica\"><i>@BBCAfrica</i></a><i>, on Facebook at </i><a href=\"https://www.facebook.com/BBCnewsafrica/\"><i>BBC Africa</i></a><i> or on Instagram at </i><a href=\"https://www.instagram.com/bbcafrica/\"><i>bbcafrica</i></a></p>",
      "links": [
        "https://www.bbc.com/",
        "https://www.bbc.com/watch-live-news/",
        "https://session.bbc.com/session?action=register&userOrigin=BBCS_BBC&ptrt=https%3A%2F%2Fwww.bbc.com%2Fnews%2Farticles%2Fcj02rvvd8g2o",
        "https://session.bbc.com/session?userOrigin=BBCS_BBC&ptrt=https%3A%2F%2Fwww.bbc.com%2Fnews%2Farticles%2Fcj02rvvd8g2o",
        "https://www.bbc.com/news",
        "https://www.bbc.com/sport",
        "https://www.bbc.com/business",
        "https://www.bbc.com/innovation",
        "https://www.bbc.com/culture",
        "https://www.bbc.com/arts",
        "https://www.bbc.com/travel",
        "https://www.bbc.com/future-planet",
        "https://www.bbc.com/video",
        "https://www.bbc.com/live",
        "https://www.bbc.com/home",
        "https://www.bbc.com/news/topics/c2vdnvdg6xxt",
        "https://www.bbc.com/news/war-in-ukraine",
        "https://www.bbc.com/news/us-canada",
        "https://www.bbc.com/news/uk",
        "https://www.bbc.com/news/politics",
        "https://www.bbc.com/news/england",
        "https://www.bbc.com/news/northern_ireland",
        "https://www.bbc.com/news/northern_ireland/northern_ireland_politics",
        "https://www.bbc.com/news/scotland",
        "https://www.bbc.com/news/scotland/scotland_politics",
        "https://www.bbc.com/news/wales",
        "https://www.bbc.com/news/wales/wales_politics",
        "https://www.bbc.com/news/world/africa",
        "https://www.bbc.com/news/world/asia",
        "https://www.bbc.com/news/world/asia/china",
        "https://www.bbc.com/news/world/asia/india",
        "https://www.bbc.com/news/world/australia",
        "https://www.bbc.com/news/world/europe",
        "https://www.bbc.com/news/world/latin_america",
        "https://www.bbc.com/news/world/middle_east",
        "https://www.bbc.com/news/in_pictures",
        "https://www.bbc.com/news/bbcindepth",
        "https://www.bbc.com/news/bbcverify",
        "https://www.bbc.com/business/executive-lounge",
        "https://www.bbc.com/business/technology-of-business",
        "https://www.bbc.com/business/future-of-business",
        "https://www.bbc.com/innovation/technology",
        "https://www.bbc.com/innovation/science",
        "https://www.bbc.com/innovation/artificial-intelligence",
        "https://www.bbc.com/innovation/ai-v-the-mind",
        "https://www.bbc.com/culture/film-tv",
        "https://www.bbc.com/culture/music",
        "https://www.bbc.com/culture/art",
        "https://www.bbc.com/culture/style",
        "https://www.bbc.com/culture/books",
        "https://www.bbc.com/culture/entertainment-news",
        "https://www.bbc.com/arts/arts-in-motion",
        "https://www.bbc.com/travel/destinations",
        "https://www.bbc.com/travel/destinations/africa",
        "https://www.bbc.com/travel/destinations/antarctica",
        "https://www.bbc.com/travel/destinations/asia",
        "https://www.bbc.com/travel/destinations/australia-and-pacific",
        "https://www.bbc.com/travel/destinations/caribbean",
        "https://www.bbc.com/travel/destinations/central-america",
        "https://www.bbc.com/travel/destinations/europe",
        "https://www.bbc.com/travel/destinations/middle-east",
        "https://www.bbc.com/travel/destinations/north-america",
        "https://www.bbc.com/travel/destinations/south-america",
        "https://www.bbc.com/travel/worlds-table",
        "https://www.bbc.com/travel/cultural-experiences",
        "https://www.bbc.com/travel/adventures",
        "https://www.bbc.com/travel/specialist",
        "https://www.bbc.com/future-planet/natural-wonders",
        "https://www.bbc.com/future-planet/weather-science",
        "https://www.bbc.com/future-planet/solutions",
        "https://www.bbc.com/future-planet/sustainable-business",
        "https://www.bbc.com/future-planet/green-living",
        "https://www.bbc.com/live/news",
        "https://www.bbc.com/live/sport",
        "https://x.com/jimNjue_/status/1869023751633080387",
        "https://x.com/ledamalekina/status/1855632388648247296",
        "https://www.bbc.co.uk/news/business-64382400",
        "https://www.bbc.co.uk/news/articles/ce77ld43lngo",
        "https://www.president.go.ke/president-ruto-announces-nationwide-livestock-vaccination/",
        "https://www.bbc.com/news/articles/cz4xn7yqe25o",
        "https://www.bbc.com/news/articles/c999n2nyvwlo",
        "https://www.bbc.com/news/articles/c133r4gyx1no",
        "https://www.bbc.co.uk/news/world-africa-62244844",
        "https://www.bbc.co.uk/news/articles/ck77g7v2dwyo",
        "http://bbcafrica.com/",
        "https://twitter.com/BBCAfrica",
        "https://www.facebook.com/BBCnewsafrica/",
        "https://www.instagram.com/bbcafrica/"
      ],
      "text": "Backlash in Kenya over livestock vaccines and belching cows\nNairobi\nGetty Images\nAn ambitious initiative to vaccinate all livestock in Kenya is due to kick off this week amid fierce resistance from farmers that is being driven by misleading claims about the vaccines.\nIt will cost farmers nothing to get their animals vaccinated as the government says it is footing the bill.\nBut Robert Nkukuu, who keeps cattle in the Mai Mahiu area of Nakuru county - some 50km (30 miles) north-west of the capital, Nairobi, explained how it had become a toxic issue since President William Ruto announced the plan last November.\n\"If the community here learns you are pro-vaccination they will slay you just now. So stop talking about it, we don't want it,\" he told the BBC.\nThe government's aim is to vaccinate at least 22 million cattle and 50 million goats and sheep over three years.\nCurrently only 10% of the national herd get the necessary vaccinations and the authorities say they want to raise that rate to 85% to make Kenya's livestock products eligible for export.\nThe president, who is a farm owner and has several big herds himself, has said the vaccines are vital for expanding the sector by controlling foot-and-mouth disease in cattle and peste des petits ruminants (PPR) - also known as sheep and goat plague.\nBut some of those who oppose the programme believe Microsoft co-founder Bill Gates is funding it, fuelled by people sharing videos of interviews featuring him talking about vaccinating cows to control methane emissions.\nAFP\nMethane expelled by livestock belching and farting contributes about 15% of global emissions each year, UN estimates show. It is the most common greenhouse gas after carbon dioxide (CO2).\nJonathan Mueke, a senior official in Kenya's agriculture ministry, has denied that Gates is involved in the livestock vaccination programme - adding that neither the US billionaire and philanthropist nor other foreign sources have provided funding.\nBut this has not stopped the conspiracy theories being circulated on social media, often by high-profile personalities.\nCaleb Karuga, a former journalist and now an influential farmer, posted on X that he would resist the jabs, saying no-one will vaccinate his livestock just \"because Bill Gates said so\".\nLedama Olekina, an opposition senator and prominent Maasai pastoralist, wrote on X: \"There [are] millions of cows in Europe and America and none of them are being vaccinated for farting … mine will not be vaccinated.\"\nGates has previously invested in projects to reduce methane emissions from cattle and is funding a US-based company looking to develop a vaccine, as are other US investors.\nBut Prof Ermias Kebreab from the University of California, Davis in the US, who has researched how to reduce methane emissions from livestock, told the BBC there was currently no livestock vaccine for reducing methane emissions in use.\n\"I wish we had one but that is still in development - and no-one has reached [the stage of] testing in animals yet,\" he said.\nHowever, such assurances have done little to quell misunderstanding about the motives of the vaccine campaign.\nThe distrust is being pushed by some opposition politicians, who have said the vaccines will alter the genetic make-up of livestock, potentially resulting in defective animals.\n\"Ruto is advancing a sinister foreign agenda. This plan is reckless and must be stopped,\" said Kalonzo Musyoka, an opposition leader, not long after the initiative was announced.\nWhen the BBC asked Musyoka about the specific claims that the vaccines could be harmful to the cattle, his spokesperson said the vaccination campaign was a \"violation of the constitution\".\nHe added that it had been \"shrouded in secrecy\" and the government had not shared details about resources, implementation or technical details about the vaccines.\nThe suggestion that livestock vaccines will genetically change animals is misleading, according to Prof Ermias.\n\"It is very similar to people getting vaccinated to fight against various diseases. There is no report that it causes deformities or alters DNA,\" the academic told the BBC.\nPresident Ruto has dismissed the views of those opposing the vaccinations as \"simply misguided, unreasonable and possibly stupid\".\n\"All of us who have been vaccinated, has anyone stopped farting?\" Ruto said as he dismissed the methane claims as \"nonsense\".\nYet analysts say the spread of such conspiracy theories is down to poor communication by Ruto himself as well as low trust in his government following anti-tax protests last year and a series of corruption scandals.\nThe government has faced a huge backlash over tax increases brought in since Ruto became president in 2022 - making it very unpopular. Last June it was forced to withdraw a controversial finance bill that would have included more tax increases.\nAlphonce Shiundu, Kenya editor at fact-checking organisation AfricaCheck, says the government was now facing a \"trust deficiency\" in the way it communicated the livestock campaign.\nWhen Ruto first announced it, details were scant - and it was not clear what the animals would be vaccinated against.\nThis is when tools that monitor social media posts on X show there was a clear spike in mentions of both Gates and cows by accounts with their location listed as Kenya.\nThe furore grew into a matter of national debate, with cartoonists even pushing for cows' rights on social media with comical images captioned \"my fart, my choice\".\nThe Kenya Veterinary Association (KVA) has called on the government to halt the vaccination exercise and conduct a public awareness campaign first.\n\"The politicisation of the vaccination exercise has adversely affected the entire campaign, thus distracting the public from the goal of controlling diseases,\" Dr Kelvin Osore, KVA chairperson, told the BBC.\nBut Dr Allan Azegele, the director of veterinary services at the agriculture ministry, said it could not be delayed given the recent severe outbreak of foot-and-mouth in western areas.\nThis has forced several livestock markets to close this month - and the authorities have imposed strict quarantine measures in those places.\n\"We cannot wait… because it is more expensive to respond to outbreaks. We have to be proactive rather than reactive,\" Dr Azegele told the BBC.\nHe said foot-and-mouth had no specific treatment, making prevention through vaccination crucial.\nAgriculture Minister Mutahi Kagwe has sought to reassure everyone that the exercise will be voluntary and has pledged to engage all stakeholders to \"cure misinformation\" surrounding the issue.\nThe government has also been reassuring the public that the vaccines are being produced locally.\nBut some farmers are still vowing to resist the vaccination drive, citing possible foreign influence and mistrust of the government.\nDavid Tiriki, a livestock farmer in Kajiado county, south of Nairobi, told the BBC that he would not allow his animals to be inoculated, citing safety fears.\n\"I suspect someone is trying to introduce a virus to our livestock so that the rich can start selling the cure to poor farmers who might not even afford it,\" he said.\nThe BBC did speak to one small-scale farmer from Makueni county, south-east of Nairobi, who welcomed the initiative.\nBut Ngemu Musau urged the government to make the whole process more transparent.\n\"I want assurance that my cattle will be OK after the vaccine,\" he told the BBC.\n\"There is a need for the government to conduct intensive public awareness campaigns.\"\nYou may also be interested in:\nVet recounts wild tales of working in Kenya\nKenya rolls out poison in bid to cull a million crows\nHow a Kenyan farmer became a champion of climate change denial\nWhy farmers like William Ruto's big ambitions\nKenyan president's humbling shows power of African youth\nGetty Images/BBC\nGo to BBCAfrica.com for more news from the African continent.\nFollow us on Twitter @BBCAfrica, on Facebook at BBC Africa or on Instagram at bbcafrica"
    }
  ]
} */
